car_inventory/__init__.py
from flask import Flask, render_template
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder


app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.config.from_object(Config)
app.json_encoder = JSONEncoder
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

car_inventory/api/routes.py
from flask import Blueprint, request, jsonify
from helpers import token_required
from models import db, User, Car, car_schema, cars_schema

api = Blueprint('api', __name__, url_prefix = '/api')

# Create car endpoint
@api.route('/cars', methods = ['POST'])
@token_required
def create_car(current_user_token):
    year = request.json['year']
    make = request.json['make']
    model = request.json['model']
    cost = request.json['cost']
    user_token = current_user_token.token

    print(f'BIG TESTER: {current_user_token.token}')

    car = Car(year, make, model, cost, user_token = user_token)
    db.session.add(car)
    db.session.commit()
    response = car_schema.dump(car)
    return jsonify(response)

# Retrieve cars endpoint
@api.route('/cars', methods = ['GET'])
@token_required
def get_all_cars(current_user_token):
    a_car = current_user_token.token
    cars = Car.query.filter_by(user_token = a_car).all()
    response = cars_schema.dump(cars)
    return jsonify(response)

# Retrieve single car endpoint
@api.route('/cars/<id>', methods = ['GET'])
@token_required
def get_single_car(current_user_token, id):
    c_owner = current_user_token.token
    if c_owner == current_user_token.token:
        car = Car.query.get(id)
        response = car_schema.dump(car)
        return jsonify(response)
    else:
        return jsonify({'Message': 'Valid Token Required'}), 401

# Update car endpoint
@api.route('/cars/<id>', methods = ['POST', 'PUT'])
@token_required
def update(current_user_token, id):
    car = Car.query.get(id)
    car.year = request.json['year']
    car.make = request.json['make']
    car.model = request.json['model']
    car.cost = request.json['cost']
    car.user_token = current_user_token.token

    db.session.commit()
    response = car_schema.dump(car)
    return jsonify(response)

# Delete car endpoint
@api.route('/cars/<id>', methods = ['DELETE'])
@token_required
def delete(current_user_token, id):
    car = Car.query.get(id)
    db.session.delete(car)
    db.session.commit()
    response = car_schema.dump(car)
    return jsonify(response)

car_inventory/authentication/routes.py
from forms import UserLoginForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def sign_up():
    form = UserLoginForm()
    
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(email, password = password)
            
            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account at {email}', 'user-created')
            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('sign_up.html', form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def sign_in():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash("You're logged in!", 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash("You email 0r password is incorrect.", 'auth-failed')
                return redirect(url_for('auth.sign_in'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('sign_in.html', form = form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

car_inventory/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

car_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600;700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../static/css/main.css">
<title>Car Inventory API</title>
</head>
<body class="bg-dark">
    <nav class="container-fluid navbar navbar-expand-md navbar-dark">
        <a href="{{ url_for('site.home') }}" class="navbar-brand text-white-50 ms-3">Car Inventory API</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end mt-2" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item p-1"><a href="{{ url_for('site.home') }}" class="nav-link btn btn-outline-secondary">Home</a></li>
                {% if current_user.is_authenticated %}
                <li class="nav-item p-1"><a href="{{ url_for('site.profile') }}" class="nav-link btn btn-outline-secondary">Profile</a></li>
                <li class="nav-item p-1"><a href="{{ url_for('auth.logout') }}" class="nav-link btn btn-outline-secondary">Log Out</a></li>
                {% else %}
                <li class="nav-item p-1"><a href="{{ url_for('auth.sign_in') }}" class="nav-link btn btn-outline-secondary">Sign In</a></li>
                <li class="nav-item p-1"><a href="{{ url_for('auth.sign_up') }}" class="nav-link btn btn-outline-secondary">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

car_inventory/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset id="email-field">
        <label for="email-field" class="fs-3 pb-2">Email:</label>
        {{ form.email(class = 'form-control', placeholder = 'Enter Email') }}
        <br>
    </fieldset>

    <fieldset id="pass-field">
        <label for="pass-field" class="fs-3 pb-2">Password:</label>
        {{ form.password(class = "form-control", placeholder = "Enter Password") }}
        <br>
    </fieldset>

    <button type = "submit" class="btn btn-primary w-25 mt-3">SUBMIT</button>
</form>